name: Flutter PR

on:
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Load java SDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Load Flutter SDK
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Clone project
        uses: actions/checkout@v1

      - name: Get dependencies
        run: flutter pub get

      - name: Code analysis
        run: flutter analyze

      - name: Build Android artifact
        run: flutter build apk --release --no-sound-null-safety